/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 148
#define YY_END_OF_BUFFER 149
static yyconst short int yy_accept[477] =
    {   0,
        0,    0,  149,  147,  146,  146,  113,  147,   98,  115,
      147,  133,  134,   96,   94,  131,   95,  132,   97,  142,
      142,  129,  130,  109,  104,  110,  128,  145,  137,  138,
      117,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  135,  116,  136,  114,  146,  106,    0,  143,    0,
      103,  111,  120,    0,    0,  101,   92,   99,   93,  100,
        0,    1,  102,    0,  142,    0,  118,  107,  105,  125,
      108,  119,  126,  145,  122,  145,  145,    4,  145,  145,
      145,  145,  145,  145,  145,  145,   16,  145,  145,  145,

      145,  145,  145,  145,  145,  145,  145,  145,  145,   28,
      145,   30,   34,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  121,  112,  144,    0,
        0,    1,  141,    0,    0,  123,  124,  127,  145,   81,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,   25,  145,   79,  145,  145,  145,   31,  145,   90,
      145,  145,  145,   38,  145,  145,  145,  145,   42,  145,

      145,  145,  145,  145,  145,   49,  145,  145,  145,  145,
      145,   80,  145,  145,  145,  145,  145,  145,  145,  145,
       63,  145,  145,  145,  145,  145,  145,  145,   78,  145,
      145,  145,  145,  145,  145,    2,  141,    0,    0,    0,
      145,  145,  145,    5,  145,    7,  145,  145,  145,  145,
      145,  145,  145,  145,  145,   17,   18,  145,  145,  145,
      145,  145,  145,  145,   85,   27,  145,  145,  145,   88,
       89,   35,   36,  145,   39,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,   60,  145,   62,  145,

       65,  145,  145,  145,  145,  145,  145,   72,  145,  145,
      145,  145,    0,  141,    0,    0,  145,   75,   76,    6,
        8,  145,   10,   11,  145,  145,  145,  145,  145,   19,
      145,  145,   22,  145,   24,  145,   87,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,   51,  145,  145,   53,  145,  145,  145,  145,  145,
      145,   61,  145,   66,  145,  145,  145,   70,  145,  145,
       86,   74,   91,    0,    0,  145,  145,  145,  145,  145,
      145,  145,  145,   21,  145,  145,  145,  145,  145,  145,
       40,  145,  145,  145,   44,  145,  145,   47,  145,   82,

       50,   52,   84,   54,  145,   56,   57,   58,   59,   64,
      145,   68,   69,  145,  145,    0,    0,  145,    9,  145,
       13,   14,  145,   77,  145,   23,   26,  145,  145,  145,
      145,  145,   83,  145,   45,  145,  145,  145,  145,   71,
      145,    0,    0,    3,   12,   15,   20,   29,  145,   33,
      145,   41,   43,  145,   48,  145,  145,   73,    0,    0,
       32,   37,   46,  145,   67,  140,    0,   55,    0,    0,
        0,    0,    0,    0,  139,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   33,   29,   29,
       34,   35,   36,   37,   29,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   29,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[67] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    1,    1,    1,    1,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[482] =
    {   0,
        0,    0,  547,  548,   65,   67,  522,   66,  521,   65,
      509,  548,  548,  519,   61,  548,   60,  548,   64,   75,
       85,  548,  548,   53,   54,   57,  516,    0,  548,  548,
      517,   57,   45,   68,   66,   70,   77,   72,   82,  488,
       45,   96,   97,   53,  497,  100,  103,  112,   97,  493,
      491,  548,   98,  548,  548,  138,  548,  139,  548,    0,
      548,  548,  548,  528,  144,  548,  548,  548,  548,  548,
      524,    0,  548,  151,  158,  121,  510,  548,  548,  548,
      548,  509,  508,    0,  548,  476,  489,  468,  490,  472,
      484,  110,  483,  486,  472,  139,    0,  471,  466,  463,

      477,  127,  469,  133,  463,  464,  459,  458,  461,    0,
      459,  455,    0,  464,  453,  145,  458,  448,  457,  458,
      462,  462,  446,  459,  446,  140,  460,  151,  437,  149,
      445,  434,  152,  449,  145,  143,  441,  442,  440,  155,
      157,  437,  436,  162,  167,  447,  548,  548,  548,  477,
      201,    0,  201,  459,  453,  548,  548,  548,  429,    0,
      433,  437,  440,  443,  438,  439,  438,  422,  159,  430,
      437,  432,  435,  430,  421,  419,  420,  426,  412,  428,
      423,  422,  413,    0,  410,  404,  411,  174,  408,    0,
      410,  413,  414,    0,  406,  412,  399,  410,    0,  397,

      412,  391,  392,  398,  405,    0,  393,  387,  387,  393,
      399,    0,  386,  397,  182,  177,  382,  382,  384,  393,
        0,  392,  377,  381,  386,  392,  377,  377,    0,  371,
      385,  387,  370,  374,  373,  548,  548,  233,  385,  384,
      365,  378,  361,    0,  368,    0,  370,  366,  358,  356,
      365,  360,  352,  364,  357,    0,    0,  350,  359,  350,
      361,  353,  360,  362,    0,    0,  346,  352,  343,    0,
        0,    0,    0,  341,    0,  355,  356,  339,  338,  341,
      352,  347,  342,  335,  328,  331,  342,  341,  342,  325,
      328,  331,  332,  326,  336,  335,    0,  315,    0,  321,

        0,  328,  329,  327,  315,  324,  310,    0,  310,  323,
      322,  322,  210,  237,  328,  327,  322,    0,    0,    0,
        0,  317,    0,    0,  307,  319,  307,  317,  308,    0,
      313,  301,    0,  302,    0,  310,    0,  309,  197,  295,
      291,  290,  306,  298,  288,  286,  301,  300,  288,  296,
      286,    0,  295,  279,    0,  291,  295,  292,  287,  274,
      284,    0,  285,    0,  287,  284,  269,    0,  286,  277,
        0,    0,    0,  305,  304,  280,  278,  261,  268,  260,
      259,  274,  267,    0,  251,  266,  264,  271,  270,  269,
        0,  254,  244,  263,    0,  261,  246,    0,  252,    0,

        0,    0,    0,    0,  251,    0,    0,    0,    0,    0,
      251,    0,    0,  249,  248,  276,  273,  226,    0,  237,
        0,    0,  235,    0,  220,    0,    0,  219,  234,  224,
      232,  217,    0,  228,    0,  226,  205,  216,  222,    0,
      221,  226,  241,    0,    0,    0,    0,    0,  218,    0,
      217,    0,    0,  217,    0,  197,  205,    0,  229,  201,
        0,    0,    0,  197,    0,  548,  222,    0,  192,  198,
      210,  165,  136,   99,  548,  548,  280,  284,   82,  288,
      292
    } ;

static yyconst short int yy_def[482] =
    {   0,
      476,    1,  476,  476,  476,  476,  476,  477,  476,  476,
      478,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  479,  476,  476,
      476,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  476,  476,  476,  476,  476,  476,  477,  476,  477,
      476,  476,  476,  476,  478,  476,  476,  476,  476,  476,
      480,  481,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  479,  476,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,

      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  476,  476,  476,  480,
      480,  481,  476,  476,  476,  476,  476,  476,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,

      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  476,  476,  476,  476,  476,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,

      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  476,  476,  476,  476,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  476,  476,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,

      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  476,  476,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  476,  476,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  476,  476,
      479,  479,  479,  479,  479,  476,  476,  479,  476,  476,
      476,  476,  476,  476,  476,    0,  476,  476,  476,  476,
      476
    } ;

static yyconst short int yy_nxt[615] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       22,   23,   24,   25,   26,   27,   28,   28,   28,   28,
       28,   28,   28,   29,    4,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   28,   39,   40,   28,   41,   28,
       42,   43,   44,   45,   46,   47,   48,   49,   50,   28,
       51,   28,   52,   53,   54,   55,   56,   56,   56,   56,
       59,   62,   67,   69,   71,   77,   78,   79,   80,   72,
       81,   82,   90,   70,   68,   84,  115,   73,   63,   74,
      125,   75,   75,   75,   75,   86,  116,   87,   91,   74,

       60,   75,   75,   75,   75,   92,  126,   96,   76,  127,
      475,   88,   93,  107,  103,   89,   94,   97,   99,   95,
      100,  147,  104,  108,  110,  109,   98,  101,  105,  102,
      106,  111,  112,  117,  142,  120,  113,  118,  129,   56,
       56,  130,  143,   59,  131,  132,  476,  135,  144,  121,
      122,   64,  119,  123,  124,  133,  136,  138,  134,  154,
      139,  148,  140,  137,  165,  166,  141,  153,  153,  153,
      153,  474,   74,   60,   75,   75,   75,   75,  170,  177,
      155,  171,  178,  180,  191,  202,  210,  172,  205,  215,
      218,  203,  181,  206,  225,  192,  473,  211,  219,  220,

      207,  227,  228,  221,  212,  216,  208,  231,  233,  226,
      232,  151,  234,  250,  251,  269,  236,  153,  153,  153,
      153,  292,  294,  472,  471,  270,  314,  314,  314,  314,
      237,  238,  237,  295,  470,  469,  468,  293,  467,  388,
      466,  237,  238,  237,  313,  465,  313,  389,  464,  314,
      314,  314,  314,  314,  314,  314,  314,  463,  462,  461,
      460,  459,  458,  457,  456,  455,  237,  454,  237,  453,
      452,  451,  450,  449,  448,  447,  446,  237,  445,  237,
       58,  444,   58,   58,   64,   64,  443,   64,  150,  150,
      150,  150,  152,  442,  152,  152,  441,  440,  439,  438,

      437,  436,  435,  434,  433,  432,  431,  430,  429,  428,
      427,  426,  425,  424,  423,  422,  421,  420,  419,  418,
      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,
      407,  406,  405,  404,  403,  402,  401,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  387,  386,
      385,  384,  383,  382,  381,  380,  379,  378,  377,  376,
      375,  374,  373,  372,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,

      335,  334,  333,  332,  331,  330,  329,  328,  327,  326,
      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  252,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  151,  235,  230,
      229,  224,  223,  222,  217,  214,  213,  209,  204,  201,

      200,  199,  198,  197,  196,  195,  194,  193,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  179,  176,  175,
      174,  173,  169,  168,  167,  164,  163,  162,  161,  160,
      159,  158,  157,  156,  151,  149,  146,  145,  128,  114,
       85,   83,   66,   65,   61,   57,  476,    3,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,

      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476
    } ;

static yyconst short int yy_chk[615] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    6,    6,
        8,   10,   15,   17,   19,   24,   24,   25,   25,   19,
       26,   26,   33,   17,   15,  479,   41,   19,   10,   20,
       44,   20,   20,   20,   20,   32,   41,   32,   33,   21,

        8,   21,   21,   21,   21,   34,   44,   35,   20,   44,
      474,   32,   34,   38,   37,   32,   34,   35,   36,   34,
       36,   53,   37,   38,   39,   38,   35,   36,   37,   36,
       37,   39,   39,   42,   49,   43,   39,   42,   46,   56,
       56,   46,   49,   58,   46,   46,   65,   47,   49,   43,
       43,   65,   42,   43,   43,   46,   47,   48,   46,   76,
       48,   53,   48,   47,   92,   92,   48,   74,   74,   74,
       74,  473,   75,   58,   75,   75,   75,   75,   96,  102,
       76,   96,  102,  104,  116,  126,  130,   96,  128,  133,
      135,  126,  104,  128,  140,  116,  472,  130,  135,  136,

      128,  141,  141,  136,  130,  133,  128,  144,  145,  140,
      144,  151,  145,  169,  169,  188,  151,  153,  153,  153,
      153,  215,  216,  471,  470,  188,  313,  313,  313,  313,
      153,  153,  153,  216,  469,  467,  464,  215,  460,  339,
      459,  153,  153,  153,  238,  457,  238,  339,  456,  238,
      238,  238,  238,  314,  314,  314,  314,  454,  451,  449,
      443,  442,  441,  439,  438,  437,  314,  436,  314,  434,
      432,  431,  430,  429,  428,  425,  423,  314,  420,  314,
      477,  418,  477,  477,  478,  478,  417,  478,  480,  480,
      480,  480,  481,  416,  481,  481,  415,  414,  411,  405,

      399,  397,  396,  394,  393,  392,  390,  389,  388,  387,
      386,  385,  383,  382,  381,  380,  379,  378,  377,  376,
      375,  374,  370,  369,  367,  366,  365,  363,  361,  360,
      359,  358,  357,  356,  354,  353,  351,  350,  349,  348,
      347,  346,  345,  344,  343,  342,  341,  340,  338,  336,
      334,  332,  331,  329,  328,  327,  326,  325,  322,  317,
      316,  315,  312,  311,  310,  309,  307,  306,  305,  304,
      303,  302,  300,  298,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  279,  278,  277,  276,  274,  269,  268,  267,  264,

      263,  262,  261,  260,  259,  258,  255,  254,  253,  252,
      251,  250,  249,  248,  247,  245,  243,  242,  241,  240,
      239,  235,  234,  233,  232,  231,  230,  228,  227,  226,
      225,  224,  223,  222,  220,  219,  218,  217,  214,  213,
      211,  210,  209,  208,  207,  205,  204,  203,  202,  201,
      200,  198,  197,  196,  195,  193,  192,  191,  189,  187,
      186,  185,  183,  182,  181,  180,  179,  178,  177,  176,
      175,  174,  173,  172,  171,  170,  168,  167,  166,  165,
      164,  163,  162,  161,  159,  155,  154,  150,  146,  143,
      142,  139,  138,  137,  134,  132,  131,  129,  127,  125,

      124,  123,  122,  121,  120,  119,  118,  117,  115,  114,
      112,  111,  109,  108,  107,  106,  105,  103,  101,  100,
       99,   98,   95,   94,   93,   91,   90,   89,   88,   87,
       86,   83,   82,   77,   71,   64,   51,   50,   45,   40,
       31,   27,   14,   11,    9,    7,    3,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,

      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\lexer.l"
#define INITIAL 0
#line 2 ".\\lexer.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Definicion para exportar funciones en Windows */
#ifdef _WIN32
  #define EXPORT __declspec(dllexport)
#else
  #define EXPORT
#endif

/* Variables globales para el manejo del bufer de salida */
static char* currentOutputBuffer = NULL;
static size_t currentBufferSize = 0;
static size_t currentOutputLength = 0;

/* Funcion auxiliar para concatenar cadenas al bufer dinamico */
static void appendOutput(const char* str) {
    size_t len = strlen(str);
    if (currentOutputLength + len + 1 > currentBufferSize) {
        currentBufferSize = (currentOutputLength + len + 1) * 2;
        currentOutputBuffer = realloc(currentOutputBuffer, currentBufferSize);
        if (!currentOutputBuffer) {
            fprintf(stderr, "Error al asignar memoria\n");
            exit(1);
        }
    }
    strcpy(currentOutputBuffer + currentOutputLength, str);
    currentOutputLength += len;
}
#line 692 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 36 ".\\lexer.l"


#line 846 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 477 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 548 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 38 ".\\lexer.l"
{ 
            appendOutput("Comentario de linea detectado\n"); 
        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 42 ".\\lexer.l"
{ 
            appendOutput("Comentario de bloque detectado\n"); 
        }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 46 ".\\lexer.l"
{ appendOutput("Palabra reservada: abstract\n"); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 47 ".\\lexer.l"
{ appendOutput("Palabra reservada: as\n"); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 48 ".\\lexer.l"
{ appendOutput("Palabra reservada: base\n"); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 49 ".\\lexer.l"
{ appendOutput("Palabra reservada: break\n"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 ".\\lexer.l"
{ appendOutput("Palabra reservada: case\n"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 51 ".\\lexer.l"
{ appendOutput("Palabra reservada: catch\n"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 52 ".\\lexer.l"
{ appendOutput("Palabra reservada: checked\n"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 53 ".\\lexer.l"
{ appendOutput("Palabra reservada: class\n"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 54 ".\\lexer.l"
{ appendOutput("Palabra reservada: const\n"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 55 ".\\lexer.l"
{ appendOutput("Palabra reservada: continue\n"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 ".\\lexer.l"
{ appendOutput("Palabra reservada: decimal\n"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 57 ".\\lexer.l"
{ appendOutput("Palabra reservada: default\n"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 58 ".\\lexer.l"
{ appendOutput("Palabra reservada: delegate\n"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 59 ".\\lexer.l"
{ appendOutput("Palabra reservada: do\n"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 60 ".\\lexer.l"
{ appendOutput("Palabra reservada: else\n"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 61 ".\\lexer.l"
{ appendOutput("Palabra reservada: enum\n"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 62 ".\\lexer.l"
{ appendOutput("Palabra reservada: event\n"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 63 ".\\lexer.l"
{ appendOutput("Palabra reservada: explicit\n"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 64 ".\\lexer.l"
{ appendOutput("Palabra reservada: extern\n"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 65 ".\\lexer.l"
{ appendOutput("Palabra reservada: false\n"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 66 ".\\lexer.l"
{ appendOutput("Palabra reservada: finally\n"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 67 ".\\lexer.l"
{ appendOutput("Palabra reservada: fixed\n"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 68 ".\\lexer.l"
{ appendOutput("Palabra reservada: for\n"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 69 ".\\lexer.l"
{ appendOutput("Palabra reservada: foreach\n"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 70 ".\\lexer.l"
{ appendOutput("Palabra reservada: goto\n"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 71 ".\\lexer.l"
{ appendOutput("Palabra reservada: if\n"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 72 ".\\lexer.l"
{ appendOutput("Palabra reservada: implicit\n"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 73 ".\\lexer.l"
{ appendOutput("Palabra reservada: in\n"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 74 ".\\lexer.l"
{ appendOutput("Palabra reservada: int\n"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 75 ".\\lexer.l"
{ appendOutput("Palabra reservada: interface\n"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 76 ".\\lexer.l"
{ appendOutput("Palabra reservada: internal\n"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 77 ".\\lexer.l"
{ appendOutput("Palabra reservada: is\n"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 ".\\lexer.l"
{ appendOutput("Palabra reservada: lock\n"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 ".\\lexer.l"
{ appendOutput("Palabra reservada: long\n"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 ".\\lexer.l"
{ appendOutput("Palabra reservada: namespace\n"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 81 ".\\lexer.l"
{ appendOutput("Palabra reservada: new\n"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 82 ".\\lexer.l"
{ appendOutput("Palabra reservada: null\n"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 83 ".\\lexer.l"
{ appendOutput("Palabra reservada: object\n"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 84 ".\\lexer.l"
{ appendOutput("Palabra reservada: operator\n"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 85 ".\\lexer.l"
{ appendOutput("Palabra reservada: out\n"); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 86 ".\\lexer.l"
{ appendOutput("Palabra reservada: override\n"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 87 ".\\lexer.l"
{ appendOutput("Palabra reservada: params\n"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 88 ".\\lexer.l"
{ appendOutput("Palabra reservada: private\n"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 89 ".\\lexer.l"
{ appendOutput("Palabra reservada: protected\n"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 90 ".\\lexer.l"
{ appendOutput("Palabra reservada: public\n"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 91 ".\\lexer.l"
{ appendOutput("Palabra reservada: readonly\n"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 92 ".\\lexer.l"
{ appendOutput("Palabra reservada: ref\n"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 93 ".\\lexer.l"
{ appendOutput("Palabra reservada: return\n"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 94 ".\\lexer.l"
{ appendOutput("Palabra reservada: sbyte\n"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 95 ".\\lexer.l"
{ appendOutput("Palabra reservada: sealed\n"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 96 ".\\lexer.l"
{ appendOutput("Palabra reservada: short\n"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 97 ".\\lexer.l"
{ appendOutput("Palabra reservada: sizeof\n"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 98 ".\\lexer.l"
{ appendOutput("Palabra reservada: stackalloc\n"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 99 ".\\lexer.l"
{ appendOutput("Palabra reservada: static\n"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 100 ".\\lexer.l"
{ appendOutput("Palabra reservada: string\n"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 101 ".\\lexer.l"
{ appendOutput("Palabra reservada: struct\n"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 102 ".\\lexer.l"
{ appendOutput("Palabra reservada: switch\n"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 103 ".\\lexer.l"
{ appendOutput("Palabra reservada: this\n"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 ".\\lexer.l"
{ appendOutput("Palabra reservada: throw\n"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 105 ".\\lexer.l"
{ appendOutput("Palabra reservada: true\n"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 106 ".\\lexer.l"
{ appendOutput("Palabra reservada: try\n"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 ".\\lexer.l"
{ appendOutput("Palabra reservada: typeof\n"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 ".\\lexer.l"
{ appendOutput("Palabra reservada: uint\n"); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 109 ".\\lexer.l"
{ appendOutput("Palabra reservada: ulong\n"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 ".\\lexer.l"
{ appendOutput("Palabra reservada: unchecked\n"); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 111 ".\\lexer.l"
{ appendOutput("Palabra reservada: unsafe\n"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 112 ".\\lexer.l"
{ appendOutput("Palabra reservada: ushort\n"); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 113 ".\\lexer.l"
{ appendOutput("Palabra reservada: using\n"); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 114 ".\\lexer.l"
{ appendOutput("Palabra reservada: virtual\n"); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 115 ".\\lexer.l"
{ appendOutput("Palabra reservada: void\n"); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 116 ".\\lexer.l"
{ appendOutput("Palabra reservada: volatile\n"); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 117 ".\\lexer.l"
{ appendOutput("Palabra reservada: while\n"); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 119 ".\\lexer.l"
{ appendOutput("Palabra reservada: async\n"); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 120 ".\\lexer.l"
{ appendOutput("Palabra reservada: await\n"); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 121 ".\\lexer.l"
{ appendOutput("Palabra reservada: dynamic\n"); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 122 ".\\lexer.l"
{ appendOutput("Palabra reservada: var\n"); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 123 ".\\lexer.l"
{ appendOutput("Palabra reservada: get\n"); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 124 ".\\lexer.l"
{ appendOutput("Palabra reservada: set\n"); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 125 ".\\lexer.l"
{ appendOutput("Palabra reservada: add\n"); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 126 ".\\lexer.l"
{ appendOutput("Palabra reservada: remove\n"); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 127 ".\\lexer.l"
{ appendOutput("Palabra reservada: orderby\n"); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 128 ".\\lexer.l"
{ appendOutput("Palabra reservada: select\n"); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 129 ".\\lexer.l"
{ appendOutput("Palabra reservada: from\n"); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 130 ".\\lexer.l"
{ appendOutput("Palabra reservada: where\n"); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 131 ".\\lexer.l"
{ appendOutput("Palabra reservada: group\n"); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 132 ".\\lexer.l"
{ appendOutput("Palabra reservada: into\n"); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 133 ".\\lexer.l"
{ appendOutput("Palabra reservada: join\n"); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 134 ".\\lexer.l"
{ appendOutput("Palabra reservada: let\n"); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 135 ".\\lexer.l"
{ appendOutput("Palabra reservada: yield\n"); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 137 ".\\lexer.l"
{ appendOutput("Operador: incremento (++).\n"); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 138 ".\\lexer.l"
{ appendOutput("Operador: decremento (--).\n"); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 139 ".\\lexer.l"
{ appendOutput("Operador: suma (+).\n"); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 140 ".\\lexer.l"
{ appendOutput("Operador: resta (-).\n"); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 141 ".\\lexer.l"
{ appendOutput("Operador: multiplicacion (*).\n"); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 142 ".\\lexer.l"
{ appendOutput("Operador: division (/).\n"); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 143 ".\\lexer.l"
{ appendOutput("Operador: modulo (%).\n"); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 144 ".\\lexer.l"
{ appendOutput("Operador: suma asignacion (+=).\n"); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 145 ".\\lexer.l"
{ appendOutput("Operador: resta asignacion (-=).\n"); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 146 ".\\lexer.l"
{ appendOutput("Operador: multiplicacion asignacion (*=).\n"); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 147 ".\\lexer.l"
{ appendOutput("Operador: division asignacion (/=).\n"); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 148 ".\\lexer.l"
{ appendOutput("Operador: modulo asignacion (%=).\n"); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 150 ".\\lexer.l"
{ appendOutput("Operador: asignacion (=).\n"); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 151 ".\\lexer.l"
{ appendOutput("Operador: igualdad (==).\n"); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 152 ".\\lexer.l"
{ appendOutput("Operador: desigualdad (!=).\n"); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 153 ".\\lexer.l"
{ appendOutput("Operador: menor o igual (<=).\n"); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 154 ".\\lexer.l"
{ appendOutput("Operador: mayor o igual (>=).\n"); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 155 ".\\lexer.l"
{ appendOutput("Operador: menor que (<).\n"); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 156 ".\\lexer.l"
{ appendOutput("Operador: mayor que (>).\n"); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 158 ".\\lexer.l"
{ appendOutput("Operador: AND logico (&&).\n"); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 159 ".\\lexer.l"
{ appendOutput("Operador: OR logico (||).\n"); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 160 ".\\lexer.l"
{ appendOutput("Operador: NOT logico (!).\n"); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 162 ".\\lexer.l"
{ appendOutput("Operador: NOT bit a bit (~).\n"); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 163 ".\\lexer.l"
{ appendOutput("Operador: AND bit a bit (&).\n"); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 164 ".\\lexer.l"
{ appendOutput("Operador: OR bit a bit (|).\n"); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 165 ".\\lexer.l"
{ appendOutput("Operador: XOR bit a bit (^).\n"); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 166 ".\\lexer.l"
{ appendOutput("Operador: desplazamiento a la izquierda (<<).\n"); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 167 ".\\lexer.l"
{ appendOutput("Operador: desplazamiento a la derecha (>>).\n"); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 168 ".\\lexer.l"
{ appendOutput("Operador: AND bit a bit asignacion (&=).\n"); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 169 ".\\lexer.l"
{ appendOutput("Operador: OR bit a bit asignacion (|=).\n"); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 170 ".\\lexer.l"
{ appendOutput("Operador: XOR bit a bit asignacion (^=).\n"); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 171 ".\\lexer.l"
{ appendOutput("Operador: desplazamiento a la izquierda asignacion (<<=).\n"); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 172 ".\\lexer.l"
{ appendOutput("Operador: desplazamiento a la derecha asignacion (>>=).\n"); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 174 ".\\lexer.l"
{ appendOutput("Operador: lambda (=>).\n"); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 175 ".\\lexer.l"
{ appendOutput("Operador: null-coalescing (??).\n"); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 176 ".\\lexer.l"
{ appendOutput("Operador: null-coalescing asignacion (??=).\n"); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 177 ".\\lexer.l"
{ appendOutput("Operador: condicional (?).\n"); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 178 ".\\lexer.l"
{ appendOutput("Operador: dos puntos (:).\n"); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 179 ".\\lexer.l"
{ appendOutput("Operador: punto y coma (;).\n"); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 180 ".\\lexer.l"
{ appendOutput("Operador: coma (,).\n"); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 181 ".\\lexer.l"
{ appendOutput("Operador: punto (.).\n"); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 183 ".\\lexer.l"
{ appendOutput("Delimitador: parentesis izquierdo (().\n"); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 184 ".\\lexer.l"
{ appendOutput("Delimitador: parentesis derecho ()).\n"); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 185 ".\\lexer.l"
{ appendOutput("Delimitador: llave izquierda ({).\n"); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 186 ".\\lexer.l"
{ appendOutput("Delimitador: llave derecha (}).\n"); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 187 ".\\lexer.l"
{ appendOutput("Delimitador: corchete izquierdo ([).\n"); }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 188 ".\\lexer.l"
{ appendOutput("Delimitador: corchete derecho (]).\n"); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 191 ".\\lexer.l"
{
    char buffer[256];
    snprintf(buffer, sizeof(buffer), "Numero hexadecimal: %s\n", yytext);
    appendOutput(buffer);
}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 197 ".\\lexer.l"
{
    char buffer[256];
    snprintf(buffer, sizeof(buffer), "Numero binario: %s\n", yytext);
    appendOutput(buffer);
}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 203 ".\\lexer.l"
{
    char buffer[256];
    snprintf(buffer, sizeof(buffer), "Numero flotante: %s\n", yytext);
    appendOutput(buffer);
}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 209 ".\\lexer.l"
{
    char buffer[256];
    snprintf(buffer, sizeof(buffer), "Numero entero: %s\n", yytext);
    appendOutput(buffer);
}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 217 ".\\lexer.l"
{
    char buffer[256];
    snprintf(buffer, sizeof(buffer), "Cadena: %s\n", yytext);
    appendOutput(buffer);
}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 224 ".\\lexer.l"
{
    char buffer[256];
    snprintf(buffer, sizeof(buffer), "Caracter: %s\n", yytext);
    appendOutput(buffer);
}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 231 ".\\lexer.l"
{
    char buffer[256];
    snprintf(buffer, sizeof(buffer), "Identificador: %s\n", yytext);
    appendOutput(buffer);
}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 238 ".\\lexer.l"
{ /* Ignorar espacios y saltos de linea */ }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 241 ".\\lexer.l"
{
    char buffer[256];
    snprintf(buffer, sizeof(buffer), "Caracter desconocido: %s\n", yytext);
    appendOutput(buffer);
}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 247 ".\\lexer.l"
ECHO;
	YY_BREAK
#line 1705 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 477 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 477 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 476);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 247 ".\\lexer.l"


/* Funcion exportada para realizar el analisis lexico. Recibe una cadena 'input'
   con el codigo a analizar y retorna un puntero a un bufer dinamico con el resultado.
   Se recomienda que, una vez procesado el resultado, se invoque LiberarMemoria para liberar la memoria asignada.
*/
EXPORT char* analizarLexico(const char* input) {
    /* Si existe un bufer previo se libera antes de iniciar un nuevo analisis */
    if (currentOutputBuffer != NULL) {
        free(currentOutputBuffer);
        currentOutputBuffer = NULL;
    }
    currentBufferSize = 1024;
    currentOutputBuffer = (char*)malloc(currentBufferSize);
    if (!currentOutputBuffer) {
        return NULL;
    }
    currentOutputBuffer[0] = '\0';
    currentOutputLength = 0;

    /* Configuramos el escaner para leer desde la cadena 'input' */
    YY_BUFFER_STATE bufferState = yy_scan_string(input);
    yylex();
    yy_delete_buffer(bufferState);

    return currentOutputBuffer;
}

/* Funcion exportada para liberar la memoria asignada al bufer generado por analizarLexico.
   El parametro 'ptr' debe ser el puntero retornado por analizarLexico.
*/
EXPORT void LiberarMemoria(char* ptr) {
    if (ptr != NULL) {
        free(ptr);
        /* Si el puntero liberado es el mismo que el global, se reinicializa */
        if (ptr == currentOutputBuffer) {
            currentOutputBuffer = NULL;
        }
    }
}

/* No se define main() ya que se compilara como DLL */
